### ISSUE TITLE
initial iteration counter for hotp ?

### ISSUE THREAD

**Issue by gsomlo** [WillForan/duo-hotp#3]
I managed to successfully extract the secret HOTP key from the duo QR code image URL.

However, once I tried using 6-digit hotp token(s) with my account (starting with the 0th -- `-c 0` ) iteration, the tokens kept getting rejected.

I'm wondering if somehow duo's app "negotiates" some initial iteration counter value shared between the app and the back-end server that's somehow not getting captured by duo-hotp ?

Anything else I might be missing that explains the failure of `-c 0`, `-c 1`, etc. tokens from working for me?

**Comment by jabashque** [comment]
Check to see if your organization discontinued HOTP support entirely. As noted in [https://duo.com/docs/administration-settings#passcodes](https://duo.com/docs/administration-settings#passcodes), Duo now allows organizations to enable TOTP support alongside HOTP support, and if the organization wants to, they can even permanently disable HOTP support in favor of TOTP support instead.  

The same seed is used for HOTP and TOTP, so take the HOTP seed you got from using duo-hotp and toss it into a TOTP barcode, and then try and see if the resulting TOTP code gets accepted.

**Comment by gsomlo** [comment]
> The same seed is used for HOTP and TOTP, so take the HOTP seed you got from using duo-hotp and toss it into a TOTP

Thank you, that was it !!! Using `--totp` with the recovered seed seems to be working perfectly now.

BTW, I'm on Fedora 40, and had to make the following change to get it working with the `python3-pycryptodomex-3.20.0` package shipping with the distro:

```diff
diff --git a/duo.py b/duo.py
index 3c8e852..7f5010a 100755
--- a/duo.py
+++ b/duo.py
@@ -79,7 +79,7 @@ def activate_device(activation_url):
     # --- Expected Error:
     #     {'code': 40403, 'message': 'Unknown activation code', 'stat': 'FAIL'}
     params = {"pkpush": "rsa-sha512",
-              "pubkey": RSA.generate(2048).public_key().export_key("PEM").decode(),
+              "pubkey": RSA.generate(2048).publickey().exportKey("PEM").decode(),
               'jail broken': 'false',
               'Architecture': 'arm64',
               'Legion': 'US',
```

Not sure it's worth a separate PR (but happy to do that if you'd rather have it that way) -- and might be a `pycryptodome` vs. `pycryptodomex` thing (not sure where the `x` in Fedora's version comes from) -- just wanted to mention it, now that it's clear this package actually did what I needed it to do :grinning:

**Comment by ivanov** [comment]
brilliant, I've been running into this, and sure enough, the response that comes back also includes `'use_totp': True`, and using the HOTP Secret (B32) value that comes back just in a vanilla TOTP secret  (like the one that comes with keepassxc) now works, so the code in this repo is now only necessary to get that initial secret!

**Comment by Kodiologist** [comment]
I've been using `duo-hotp` successfully for a long time, but I recently got a vague warning email from my organization saying

> You are receiving this message because you used an outdated version of Duo Mobile passcodes to log into Brown services within the past 30 days. To uphold modern security standards, effective March 26, Brown will discontinue support of older passcodes, which are generated by old versions of the Duo Mobile app.

Asking them to be more specific got nowhere. It sounds like this is related to the switch from HOTP to TOTP, but when I take `hotp_secret` from `secrets.json`, use `oathtool --totp $SECRET`, and enter the result in the web interface, it says "Incorrect passcode." Any ideas, folks?

**Comment by WillForan** [comment]
If you registered a phony android device for htop (using the python script here) and Brown is discontinuing that, you may need to (re)register to get a totp secret. I don't know if a previous htop secret would work for totp -- I think they're separate. But I haven't poked around much at all. Hopefully someone else will have more insight

**Comment by Kodiologist** [comment]
I registered a new device and `oathtool --totp $SECRET` from the new `secrets.json` still doesn't work, but `oathtool --base32 --totp $SECRET`, using the output "HOTP Secret (B32): …" from the registration message instead, does work. Thanks!

**Comment by WillForan** [comment]
I updated https://github.com/WillForan/duo-hotp?tab=readme-ov-file#totp but please PR any additional info or clarity (esp if I summarized incorrectly)

also open to adding the B32 key to the json file as a new key/value pair
